const constants = {
  CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',
  FETCH_FRIENDS_PENDING: 'FETCH_FRIENDS_PENDING',
  FETCH_FRIENDS_SUCCESS: 'FETCH_FRIENDS_SUCCESS',
  FETCH_FRIENDS_FAILURE: 'FETCH_FRIENDS_FAILURE',
}

export default constants